### ISSUE TITLE
Makefile update to build on Raspberry Pi

### ISSUE THREAD

**Issue by llamatrails** [LinuxCNC/mesaflash#42]
The current Makefile provides partial support for the sys/io.h stubs implementation, missing is an obvious way to enable it.

Please update the Makefile with the following:

   #enable for sys/io.h stubs implementation
   #USE_STUBS = 1

A Raspberry Pi build note in the README.md file:

    To build on a Raspberry Pi:
       Edit the Makefile to enable for sys/io.h stubs implementation.

**Comment by SebKuzminsky** [comment]
We currently build mesaflash on Raspberry Pi running the Debian Buster distribution, and I don't see any mention of Raspberry Pi in the mesaflash README.  Is `USE_STUBS` needed to build on Raspbian?

**Comment by jepler** [comment]
It appears that `outb` is provided by the system C library on current versions of raspberry pi os (raspbian):
```
$ LD_DEBUG=bindings LD_BIND_NOW=1 ./mesaflash 2>&1 | grep outb
     32145:	binding file ./mesaflash [0] to /lib/arm-linux-gnueabihf/libc.so.6 [0]: normal symbol `outb' [GLIBC_2.4]
```

It seems that information about STUBS is not needed for current raspbian and potentially should be removed. (I filed #43 to do this)

FWIW the stubs are supposed to provide implementations that allow linking but do not do anything useful.  If this is about trying to use a PCI board with mesaflash, here be dragons.  I'd love to see it work, though.

**Comment by llamatrails** [comment]
I appreciate your looking into this.  I was trying to build mesaflash on a 64bit RaspberryPi 4 4GB.  When a simple 'make' didn't compile, I started digging.  When I found the USE_STUBS in the Makefile fixed the compile problems, I then opened this issue to update the Makefile and add a note to the README.md for others.

Here is what I have run into.
$ lsb_release -a :
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ uname -a :
Linux raspi4 5.10.25-rt35-v8 #1 SMP PREEMPT_RT Sat Apr 3 09:45:47 CEST 2021 aarch64 GNU/Linux

$ git clone https://github.com/LinuxCNC/mesaflash.git

$ make :
...
gcc -O0 -g -Wall -Werror=format -Werror=format-security -std=c99 -D_GNU_SOURCE  -c epp_boards.c
epp_boards.c:22:10: fatal error: sys/io.h: No such file or directory
 #include <sys/io.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:109: epp_boards.o] Error 1

$ grep sys/io.h *.c :
eeprom_local.c:#include <sys/io.h>
epp_boards.c:#include <sys/io.h>
pci_boards.c:#include <sys/io.h>

The above three files all fail to compile, unless USE_STUBS is enabled in the Makefile.

I understand that the 64bit OS may not be officially supported yet for mesaflash.  I now have my 7c81 card working perfectly with mesaflash, and hope this may help someone in the future.  USE_STUBS may not be the solution going forward.

**Comment by jepler** [comment]
Ah, aarch64 may indeed be different.  I was looking at a traditional 32-bit userspace version.
