### ISSUE TITLE
Release versions after 3.4.2

### ISSUE THREAD

**Issue by iromero91** [LinuxCNC/mesaflash#74]
Hi, I am the proud owner of a shiny new 7i96s card and i have gotten recommendations to build this tool from source, as the tool currently on Debian repos is outdated. I see that your code identifies itself as 3.4.6, but in the Debian control files there is no changelog after 3.4.2. Would a PR be accepted to update that so that the ball can get rolling on the packaging side?

Thanks!

**Comment by SebKuzminsky** [comment]
Hi @iromero91, I'm planning to update the mesaflash package in Sid today.

**Comment by iromero91** [comment]
Thanks a lot!
